### ISSUE TITLE
Migrate Aiken UPLC crate into Pallas

### ISSUE THREAD

**Issue by rvcas** [txpipe/pallas#218]
Pretty soon it'll be time to start moving over the `uplc` crate into a crate in this monorepo. Perhaps named `pallas-plutus`.

This will serve as a parent issue to divisible subtasks so that anyone can help out.

I think most of the things can be copied and pasted over. But this might also be a chance to improve somethings as well.

Once this is complete we can deprecate `uplc` in favor of `pallas-plutus`

## Items to bring over (non-exhaustive)

- [ ] Untyped Plutus Core ast
- [ ] probably UPLC parsing 
  - [ ] potentially enhance error messages with miette
- [x] UPLC flat encoding and decoding
- [ ] UPLC machine
- [ ] phase two evaluation stuff

**Comment by scarmuega** [comment]
@rvcas should we consider this issue closed?

**Comment by rvcas** [comment]
@scarmuega yea, we'll approach is slightly differently as Amaru moves along
