### ISSUE TITLE
Revisit choice of CBOR library

### ISSUE THREAD

**Issue by scarmuega** [txpipe/pallas#26]
Opening this issue to collectively discuss alternatives to CBOR-handling libraries. I'll append my own findings from when I first evaluated minicbor and similar libraries. If a more suitable candidate is selected, we can work on the appropriate changes.

**Comment by NicolasDP** [comment]
What is the reason to revisit this choice ?

**Comment by scarmuega** [comment]
It was brought to my attention that other options might be better (serde_cbor in particular) since we're already using serde for other purposes downstream (Oura in particular).

At the very beginning of the project, I evaluated the available options and minicbor showed the following benefits:

- active development
- flexible derive API

Given the ad-hoc nature of the rules that Cardano uses for the ledger, I still think this is the correct choice. I opened this issue to have an open discussion of the tradeoffs.

**Comment by scarmuega** [comment]
After further evaluation and no contradicting opinions, I stand by the initial call of using minicbor. It strikes a good balance between ergonomics for simple derivable structs and manual low-level manipulation when needed. The project also shows very good activity providing fixes and improvements.
