### ISSUE TITLE
Is this compatible with Cardano Node >= 8.x.x ?

### ISSUE THREAD

**Issue by oskin1** [txpipe/pallas#281]

**Comment by scarmuega** [comment]
It is compatible at the networking level, but the still un-released Conway era changes are not yet supported at the ledger level.

Have you experienced any issues connecting to 8.x.x?

**Comment by oskin1** [comment]
I had issues with LocalTxSubmission (Haskell), but pallas doesn't have this protocol yet, so my question can be discarded.
