### ISSUE TITLE
feat: generate genesis UTxOs from config files

### ISSUE THREAD

**Issue by scarmuega** [txpipe/pallas#288]
We need to generate the initial set of UTxOs from genesis config files. That means reading the AVVM and non-AVVM entries of the config and then computing the corresponding address / tx id using some obscure conventions.

**Comment by scarmuega** [comment]
@jmhrpr most of the work is already done in #59, but something must be missing because resulting tx ids doesn't seem to match what I see in explorers.

**Comment by rvcas** [comment]
@scarmuega maybe this is helpful

https://github.com/dcSpark/carp/blob/main/indexer/tasks/src/genesis/genesis_txs.rs
