### ISSUE TITLE
Due diligence for storage layer planning

### ISSUE THREAD

**Issue by scarmuega** [txpipe/pallas#30]
In order to start planning a roadmap for the development of the storage layer, we need some due diligence on the state of existing Rust libraries to avoid overlap with other open-source development efforts.

In particular, we need to research:

- is there an existing Rust implementation of the ChainDB component?
- should Pallas be binary-compatible a the file system level with the Haskell implementation?

cc @mark-stopka

**Comment by mark-stopka** [comment]
Jormungandr uses SQLite

**Comment by NicolasDP** [comment]
have a look at this one https://github.com/input-output-hk/rust-cardano/tree/master/storage

**Comment by mark-stopka** [comment]
> have a look at this one https://github.com/input-output-hk/rust-cardano/tree/master/storage

I [made a fork](https://github.com/2nd-Layer/rust-cardano) and will see how will the crates build when dependencies are updated...
