### ISSUE TITLE
`InvalidCbor` error when reading blocks from `sanchonet` on `Conway` era

### ISSUE THREAD

**Issue by jpraynaud** [txpipe/pallas#410]
## Context & versions
It looks like the blocks produced by the `8.8.0-pre` Cardano node on the `sanchonet` network for the `Conway` era are not correctly parsed by Pallas `0.23.0`

## Steps to reproduce
We have tried to parse the blocks from latest immutable files produced on the `sanchonet` network with `pallas-hardano` and `pallas-traverse`:

```rust
let chunk = pallas_hardano::storage::immutable::chunk::read_blocks(Path::new("./immutable"), "05110").unwrap();

for block in chunk {
    let block = block.unwrap();
    pallas_traverse::MultiEraBlock::decode(&block).unwrap();
}
```

The immutable files are available on this [Mithril snapshot](https://storage.googleapis.com/cdn.aggregator.testing-sanchonet.api.mithril.network/sanchonet-e257-i5149.7d6ac3f583b1208a6999ddc5626c39087addb1f012a48d573c039c55ec621e2a.tar.zst)

## Actual behavior
We have received the error:
```
called `Result::unwrap()` on an `Err` value: InvalidCbor("unexpected type tag at position 864: expected array")
```

## Expected behavior
The code should not have panicked and parsed a valid `MultiEraBlock`.

**Comment by jpraynaud** [comment]
Hi @scarmuega, it looks like there are some blocks produced on Sanchonet network that are still not correctly parsed.

Here is a log extract from a Mithril node running a `pallas-hardano` parser: 
[parse-errors-tx-sanchonet-pallas-hardano.logs.txt](https://github.com/txpipe/pallas/files/14649375/parse-errors-tx-sanchonet-pallas-hardano.logs.txt)

From what I see the errors are still due to `Invalid CBOR structure` but there are several causes (at least the following ones):
- `unexpected type null at position XXX: expected array`
- `decode error: invalid variant for script enum`
- `unexpected type tag at position XXX: expected array`

Let me know if I need to create another issue or re-opening this one is fine :slightly_smiling_face:

**Comment by jmhrpr** [comment]
Please can you provide the file as you did before? I will take a look today

**Comment by jpraynaud** [comment]
Yes you can use this [snapshot](https://storage.googleapis.com/cdn.aggregator.testing-sanchonet.api.mithril.network/sanchonet-e278-i5565.c7907255f50dfc2fa22c879d07323cf3e01432f8a58c1c1a057b93312d0a6e55.tar.zst)

**Comment by jmhrpr** [comment]
Thank you, there is a PR which can successfully decode all these blocks. Do let me know if you run into any other issues

**Comment by jpraynaud** [comment]
Thanks for the fix :slightly_smiling_face:

**Comment by jpraynaud** [comment]
Hi @jmhrpr @scarmuega,

I have noticed a problem in the parsing of blocks for the immutable file `06470.chunk` in `Sanchonet` network.

Here is the error message that I receive:
```bash
Invalid CBOR structure: 18446744073709551615 overflows target type at position 1068: when converting u64 to u32
```

The immutable file is available in this [snasphot](https://storage.googleapis.com/cdn.aggregator.testing-sanchonet.api.mithril.network/sanchonet-e336-i6724.e647f8f5085a5f13e4b65a01f98163856a11df62063c32aba31d6f4b4f1a11c9.tar.zst)

Thanks for your support :slightly_smiling_face:

**Comment by scarmuega** [comment]
> ```shell
> Invalid CBOR structure: 18446744073709551615 overflows target type at position 1068: when converting u64 to u32
> ```

@jpraynaud fixed by #462

**Comment by jpraynaud** [comment]
> @jpraynaud fixed by #462

Thanks @scarmuega!

**Comment by jpraynaud** [comment]
Hi @jmhrpr @scarmuega,

I have noticed another problem in the parsing of blocks for the immutable file `07271.chunk` in `Sanchonet` network.

Here is the error message that I receive (which is very similar to the previous overflow you fixed):

```
Invalid CBOR structure: 9223372036854775807 overflows target type at position 1242: when converting u64 to u32
```

We are running the version `0.27.0` of `pallas`.

The immutable file is available in this [snasphot](https://storage.googleapis.com/cdn.aggregator.testing-sanchonet.api.mithril.network/sanchonet-e365-i7303.761a2e6d4ec095f7699122dc16ef76bee85f83c856bff5afee9697ab736d6d97.tar.zst).

Thanks for your support!

**Comment by scarmuega** [comment]
@jpraynaud on it

**Comment by scarmuega** [comment]
@jpraynaud I sent PR #473 to increase the uint size that was failing.

Regardless, I think that the Tx with issues is not compatible with the official CDDL:
https://github.com/IntersectMBO/cardano-ledger/blob/cb30d895b866ccd5d8c529212208aca0c913b9c2/eras/conway/impl/cddl-files/conway.cddl#L402C11-L402C23

The value found in the Tx is `18446744073709551615` which doesn't fit in a `uint .size 2`

**Comment by scarmuega** [comment]
submitted to ledger repo here: https://github.com/IntersectMBO/cardano-ledger/issues/4421
