### ISSUE TITLE
AuxiliaryData encoding is not using uint keys

### ISSUE THREAD

**Issue by SebastienGllmt** [txpipe/pallas#88]
The line [here](https://github.com/txpipe/pallas/blob/main/pallas-primitives/src/alonzo/model.rs#L1364) uses the type `transaction_metadata: &KeyValuePairs<Metadatum, Metadatum>` which doesn't match the Cardano binary spec. While `Metadatum` uses `int`, [the spec](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L326) has a special type for top-level keys called `transaction_metadatum_label` which uses uint instead.

Concretely, you can see in [this transaction](https://cardanoscan.io/transaction/38179200acbf327de39d8e004f65dc27635bc179a848415a870f74ab50a6a140?tab=metadata) that the metadata representation used by Oura ends up being `82a21b12127f810d7dcee28264594554491907e53b08ef38d198e051b4a080` which gives the following cbor.me representation:

```
82                        # array(2)
   A2                     # map(2)
      1B 12127F810D7DCEE2 # unsigned(1302243434517352162)
      82                  # array(2)
         64               # text(4)
            59455449      # "YETI"
         19 07E5          # unsigned(2021)
      3B 08EF38D198E051B4 # negative(643795744601428404)
      A0                  # map(0)
   80                     # array(0)

```

As you can see, instead of the expected `17802948329108123211` key, we instead get `-643795744601428404`

You can see, for example, Cardano Multiplatform Lib uses the special label type [here](https://github.com/dcSpark/cardano-multiplatform-lib/blob/develop/rust/src/metadata.rs#L277)

**Comment by scarmuega** [comment]
thanks @SebastienGllmt. Nice catch, the metadatum label should indeed be a uint instead of the current representation.

Regardless of the required change, is it possible that you're using an old version of Oura / Pallas to generate the CBOR? The current version of the lib represents INT metadatum using a minicbor struct that allows up to 2^64, which should be able to accommodate the mentioned value.

I've downloaded the block and decoded it. The rust representation of the auxiliary data shows me:

```
[
    (
        Int(
            Int {
                neg: false,
                val: 1302243434517352162,
            },
        ),
        Array(
            Def(
                [
                    Text(
                        "YETI",
                    ),
                    Int(
                        Int {
                            neg: false,
                            val: 2021,
                        },
                    ),
                ],
            ),
        ),
    ),
    (
        Int(
            Int {
                neg: false,
                val: 17802948329108123211,
            },
        ),
        Map(
            Def(
                [],
            ),
        ),
    ),
],
```

**Comment by SebastienGllmt** [comment]
I'm using Oura 1.3

Here are all the steps more concretely:

```rust
let event = input.recv()?;
let data = event.data.clone();
match data {
  EventData::Block(block_record) => {
    let alonzo::BlockWrapper(_, block) = alonzo::BlockWrapper::decode_fragment(payload);
    let aux_data = alonzo_block
            .auxiliary_data_set
            .iter()
            .find(|(index, _)| *index as usize == idx);
    let auxiliary_data = aux_data.map(|(_, a)| {
        let auxiliary_data_payload = a.encode_fragment().unwrap();
        println!("{:?}", auxiliary_data_payload);
    }
  }
}
```
